"""Leakage-safe D-1 14:00 historical replay orchestration."""
from __future__ import annotations

import pandas as pd

from backend.data import load_events, load_grid, operational_grid
from backend.intelligence.community_forecasting import (
    COMMUNITY_ARTIFACT, CommunityForecastBundle, forecast_index, issue_timestamp,
    load_causal_operational_grid, load_community_bundle,
)
from backend.intelligence.decision_engine import DecisionPolicy, recommend_events
from backend.intelligence.forecast_metrics import forecast_metrics
from backend.intelligence.peak_detection import boolean_windows, detect_risk_windows


def _actual_day(target_date: object) -> pd.DataFrame:
    index = forecast_index(target_date)
    actual = operational_grid(load_grid()).set_index("timestamp").reindex(index).rename_axis("timestamp").reset_index()
    actual = actual.rename(columns={"households_consumption_kw":"actual_demand_kw",
        "steg_production_kw":"actual_steg_kw","pv_production_kw":"actual_pv_kw",
        "available_supply_kw":"actual_supply_kw","margin_kw":"actual_margin_kw"})
    return actual


def replay_day(target_date: object, *, bundle: CommunityForecastBundle | None = None,
               policy: DecisionPolicy = DecisionPolicy()) -> dict:
    day, issue = pd.Timestamp(target_date).normalize(), issue_timestamp(target_date)
    if not pd.Timestamp("2025-01-09") <= day <= pd.Timestamp("2025-12-31"):
        raise ValueError("Replay date must be between 2025-01-09 and 2025-12-31.")
    model = bundle or load_community_bundle(str(COMMUNITY_ARTIFACT))
    causal = load_causal_operational_grid()
    forecast = model.predict_day(causal, day)
    risks = detect_risk_windows(forecast, safety_margin_kw=policy.safety_margin_kw)
    recommendations = recommend_events(forecast, risks, issue_time=issue,
        model_version=model.metadata["model_version"], policy=policy)
    actual = _actual_day(day)
    combined = forecast.merge(actual, on="timestamp", how="left")
    causal_actual = causal.set_index("timestamp").reindex(forecast_index(day))
    events = load_events()
    historical_events = events.loc[(events.start_ts < day + pd.DateOffset(days=1)) & (events.end_ts > day)].copy()
    causal_supply = causal_actual.steg_production_kw + causal_actual.pv_production_kw
    demand_metrics = forecast_metrics(causal_actual.households_consumption_kw, combined.predicted_demand_kw)
    supply_metrics = forecast_metrics(causal_supply, combined.predicted_supply_kw)
    actual_peak_windows = boolean_windows(combined.timestamp, combined.is_dr_peak.fillna(0))
    return {
        "prediction_issue_timestamp":issue,"target_day":day,"forecast_horizon":forecast_index(day),
        "model_name":model.metadata["model_name"],"model_version":model.metadata["model_version"],
        "forecast":forecast,"actual_observations":actual,"comparison":combined,
        "candidate_peak_windows":risks,"recommended_dr_events":recommendations,
        "historical_operator_events":historical_events,"actual_peak_windows":actual_peak_windows,
        "forecast_metrics":{"demand":demand_metrics,"supply":supply_metrics},
        "source_quality":{"display_uses_completed_canonical_observations":True,
            "demand_slots_with_source_gaps":int(causal_actual.households_consumption_kw_coverage.lt(1).sum()),
            "pv_slots_with_source_gaps":int(causal_actual.pv_production_kw_coverage.lt(1).sum()),
            "peak_label_slots_with_source_gaps":int(causal_actual.is_dr_peak_coverage.lt(1).sum())},
        "policy":policy,
        "status":"Simulated decision generated by the model during historical replay.",
    }


def replay_range(start_date: object, end_date: object, **kwargs) -> list[dict]:
    return [replay_day(day, **kwargs) for day in pd.date_range(start_date, end_date, freq="1D")]
